### ISSUE TITLE
Document Models

### ISSUE THREAD

**Issue by buesst1** [Sensor-Based-Activity-Recognition/docs#12]
- [x] Document Histgradient @buesst1 
- [x] Document Adaboost @yvokeller 
- [x] CNN @florinbarbisch 
- [x] MLP @gabrieltorresgamez 

-> Focus on segment based train-test split

Why segment based evaluation:
- Not enough persons in data

**Comment by gabrieltorresgamez** [comment]
@florinbarbisch Add DAG
